# Generated by Django 4.2 on 2023-04-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodboard',
            name='board',
        ),
        migrations.AlterField(
            model_name='moodboard',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Boards',
        ),
    ]
