# Generated by Django 4.2 on 2023-04-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodboard',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
