# Generated by Django 4.2 on 2023-05-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_moodboard_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Labels',
        ),
    ]
